#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int pRedChannel, pGreenChannel, pBlueChannel;//create floating variables for the rgb 
	getColorRawRGB(colorSensor, pRedChannel, pGreenChannel, pBlueChannel);//initialize
	resetMotorEncoder(leftMotor);
	//move arm up
	setMotorTarget(armMotor, 40, 90);
	waitUntilMotorStop(armMotor);
	//turn 90deg right to check if line is right of sensor
	int colorValue = getColorReflected(colorSensor);
	int temp = 0;//Needed to run the sensor briefly to get more accurate reading
	while(temp<=5){
		colorValue = getColorReflected(colorSensor);
		sleep(10);
		temp++;
	}
	while (getColorReflected(colorSensor) > 40 && getMotorEncoder(leftMotor) < 180) {
		setMotorSpeed(leftMotor, 5);//rotate right to ~90deg.
		setMotorSpeed(rightMotor, -5);
	}
	//the line is not on the right of the sensor, return and line track assuming line is left of sensor
	if (getMotorEncoder(leftMotor) > 179) {
		//return to origin position.
		resetMotorEncoder(leftMotor);
		resetMotorEncoder(rightMotor);
		setMotorTarget(leftMotor, -180, 5);//rotate left ~90deg. to origin
		setMotorTarget(rightMotor, 180, 5);
		waitUntilMotorStop(leftMotor);
		waitUntilMotorStop(rightMotor);
		//line must be left of sensor, linetrack until at box
		while (getUSDistance(sonarSensor) >= 4) {
			//line track w/line left of sensor
			//drift left
			setMotorSpeed(rightMotor, 20);
			setMotorSpeed(leftMotor, 5);
			//see line? yes, drift right
			while (getColorReflected(colorSensor) < 40) {
				setMotorSpeed(rightMotor, 0);
				setMotorSpeed(leftMotor, 30);
			}
		}
		//lower arm to trap box
		setMotorTarget(armMotor, -60, 90);
		int temp = 0;//Needed to run the sensor briefly to get more accurate reading
		while(temp<=5){
			colorValue = getColorRawRGB(colorSensor, pRedChannel, pGreenChannel, pBlueChannel);
			sleep(10);
			temp++;
		}
		//line track w/line left of sensor until at destination
		while (pRedChannel >= 34 && pRedChannel < 235) {
			getColorRawRGB(colorSensor, pRedChannel, pGreenChannel, pBlueChannel);
			//drift left
			setMotorSpeed(rightMotor, 20);
			setMotorSpeed(leftMotor, 5);
			//see black line? yes, drift right
			while (pRedChannel < 33) {
				getColorRawRGB(colorSensor, pRedChannel, pGreenChannel, pBlueChannel);
				setMotorSpeed(rightMotor, 0);
				setMotorSpeed(leftMotor, 30);
			}
		}
		//raise arm, celebrate victory
		setMotorTarget(armMotor, 50, 90);
		setMotorSpeed(leftMotor, 0);
		setMotorSpeed(rightMotor, 0);
		displayCenteredBigTextLine(8, "VICTORY!");
		sleep(5000);
	}//end of if
	//line IS to the right of sensor, track until at box
	else {
		while (getUSDistance(sonarSensor) >= 4) {
			//line track w/line right of sensor
			//drift right
			setMotorSpeed(rightMotor, 5);
			setMotorSpeed(leftMotor, 20);
			//see line? yes, drift left
			while (getColorReflected(colorSensor) < 40) {
				setMotorSpeed(rightMotor, 30);
				setMotorSpeed(leftMotor, 0);
			}
		}
		//lower arm to trap box
		setMotorTarget(armMotor, -60, 90);
		//line track w/line right of sensor until at destination
		int temp = 0;//Needed to run the sensor briefly to get more accurate reading
		while(temp<=5){
			colorValue = getColorRawRGB(colorSensor, pRedChannel, pGreenChannel, pBlueChannel);
			sleep(10);
			temp++;
		}
		while (pRedChannel >= 34 && pRedChannel < 235) {
			getColorRawRGB(colorSensor, pRedChannel, pGreenChannel, pBlueChannel);
			//drift right
			setMotorSpeed(rightMotor, 5);
			setMotorSpeed(leftMotor, 20);
			//see black line? yes, drift left
			while (pRedChannel < 34) {
				getColorRawRGB(colorSensor, pRedChannel, pGreenChannel, pBlueChannel);
				setMotorSpeed(rightMotor, 30);
				setMotorSpeed(leftMotor, 0);
			}
		}
		//raise arm, celebrate victory
		setMotorTarget(armMotor, 50, 90);
		setMotorSpeed(leftMotor, 0);
		setMotorSpeed(rightMotor, 0);
		displayCenteredBigTextLine(8, "VICTORY!");
		sleep(5000);
	}//end of else
}
