#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//move the arm up
	setMotorTarget(armMotor, 40, 90);
	waitUntilMotorStop(armMotor);
	//move up to box
	while(getUSDistance(sonarSensor)>=4){
		setMotorSpeed(rightMotor,30);
		setMotorSpeed(leftMotor,30);
	}
	//stop motors
	setMotorSpeed(rightMotor,0);
	setMotorSpeed(leftMotor,0);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);

	//lower the arm to trap the box
	setMotorTarget(armMotor, -69, 90);

	//Line track
	while(getMotorEncoder(leftMotor)<3600){
		//drift left
		setMotorSpeed(rightMotor,20);
		setMotorSpeed(leftMotor,5);
		//see line? yes, drift right
		while(getColorReflected(colorSensor)<40){
			setMotorSpeed(rightMotor,0);
			setMotorSpeed(leftMotor,30);
		}
	}
	//stop motors, raise arm, display
	setMotorSpeed(rightMotor,0);
	setMotorSpeed(leftMotor,0);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);
	setMotorTarget(armMotor, 40, 90);
	displayCenteredTextLine(8, "Delivery Successful");
	sleep(1200);
	eraseDisplay();
	sleep(1000);
	displayCenteredTextLine(8, "Delivery Successful");
	sleep(1000);
	eraseDisplay();
	sleep(1000);
	displayCenteredTextLine(8, "Delivery Successful");
	sleep(1000);
	eraseDisplay();
	sleep(1000);

}