#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int speed = 5;
task main()
{
	//go up to start of barcode; start up light sensor to skip initial value
	int temp=0;
	while (temp<5){
		getColorReflected(colorSensor);
		temp++;
		sleep(200);
	}
	/*while (getColorReflected(colorSensor)>40){
	displayCenteredBigTextLine(2, "ColorValue %d",getColorReflected(colorSensor));
	setMotorSpeed(rightMotor,speed);
	setMotorSpeed(leftMotor,speed);
	}*/

	//stop at start of barcode
	setMotorSpeed(rightMotor,0);
	setMotorSpeed(leftMotor,0);
	waitUntilMotorStop(rightMotor);
	waitUntilMotorStop(leftMotor);

	//flush data on file
	displayCenteredBigTextLine(2, "BARCODE READ");
	datalogFlush();
	datalogClose();
	datalogClear();

	// Argument 1: Datalog index; Argument 2: Columns; Argument 3: Append option
	bool datalogOpenSuccess = datalogOpen(0, 1, false);
	if (!datalogOpenSuccess) {
		displayCenteredBigTextLine(6, "Unable to open datalog.");
	}
	//datalog
	//Adjust motor encoder to length of barcode; Adjust speed if in RVW or physical world
	while(getMotorEncoder(leftMotor)<360) {
		setMotorSpeed(leftMotor, speed);
		setMotorSpeed(rightMotor, speed);
		datalogDataGroupStart();
		datalogAddValue(1, getColorReflected(colorSensor));
		sleep(100);
		datalogDataGroupEnd();
	}
	//close the log file
	datalogClose();
}
